---
title: "Housing Prices Analysis"
author: "Mandey Brown, Megan Dunnahoo, Emma Hamilton"
output: html_document
---

```{r setup, results='hide', warning=FALSE, message=FALSE}
library(knitr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(GGally)
library(tree)
library(ISLR)

```

```{r}
#reproducibility
set.seed(445)
```

```{r}

test <- read.csv("/cloud/project/test.csv")
train <- read.csv("/cloud/project/train.csv")

```

Exploratory Data Analysis

```{r explore}
# See how time variables effect sale price
ggplot(train, aes(x=YrSold, y=SalePrice)) +
  geom_point() +
  stat_summary(fun = "mean", geom = "point", color="red") +
  stat_summary(fun = "median", geom = "point", color="blue") +
  ggtitle("Year Sold vs Sale Price") + xlab("Year Sold")
ggplot(train, aes(x=MoSold, y=SalePrice)) +
  geom_point() +
  stat_summary(fun = "mean", geom = "point", color="red") +
  stat_summary(fun = "median", geom = "point", color="blue") +
  ggtitle("Month Sold vs Sale Price") + xlab("Month Sold")
ggplot(train, aes(x=YearBuilt, y=SalePrice)) +
  geom_point() +
  stat_summary(fun = "mean", geom = "point", color="red") +
  stat_summary(fun = "median", geom = "point", color="blue") +
  ggtitle("Year Built vs Sale Price") + xlab("Year Built")
ggplot(train, aes(x=YearRemodAdd, y=SalePrice)) +
  geom_point() +
  stat_summary(fun = "mean", geom = "point", color="red") +
  stat_summary(fun = "median", geom = "point", color="blue") +
  ggtitle("Year Remodeled vs Sale Price") + xlab("Year Remodeled")

# Size indicator variables
df_size <- train %>% select(c(GrLivArea, TotalBsmtSF, BsmtFullBath, BsmtHalfBath, TotRmsAbvGrd, FullBath, HalfBath, BedroomAbvGr, KitchenAbvGr, GarageArea, SalePrice))

ggpairs(df_size)

# Condition/quality variables
df_qual <- train %>% select(c(OverallQual, ExterQual, HeatingQC, KitchenQual, BsmtQual, FireplaceQu, GarageQual, PoolQC, Fence, SalePrice))

ggpairs(df_qual)

# Condition variables
df_cond <- train %>% select(c(OverallCond, ExterCond, BsmtCond, GarageCond, SalePrice))

ggpairs(df_cond)

```

Missing Values

```{r, warning=FALSE, message=FALSE}
#deal with NA/missing values

#get sum of missing values per column
cbind(lapply(lapply(train, is.na), sum))

#get percentage missing values per column
mv <- train %>% summarize_all(funs(sum(is.na(.)) / length(.)))

#find which columns have a missing percentage higher then 45%
#and remove them
which(mv > 0.45)
train <- train[-c(7, 58, 73:75)]

#replace the remaining values with mean/mode appropriately
train$LotFrontage[is.na(train$LotFrontage)] <- round(mean(train$LotFrontage, na.rm = TRUE))
train$GarageYrBlt[is.na(train$GarageYrBlt)] <- round(mean(train$GarageYrBlt, na.rm = TRUE))
#train$train$GarageYrBlt <- as.integer(train$GarageYrBlt)

calc_mode <- function(x){
  # List the distinct / unique values
  distinct_values <- unique(x)
  
  # Count the occurrence of each distinct value
  distinct_tabulate <- tabulate(match(x, distinct_values))
  
  # Return the value with the highest occurrence
  distinct_values[which.max(distinct_tabulate)]
}

train <- train %>% 
  mutate(across(everything(), ~replace_na(.x, calc_mode(.x))))

```

Convert Types

```{r}
#sapply(train, class)
#convert integer type to numeric
#convert character to factor
train <- as.data.frame(unclass(train), stringsAsFactors = TRUE)
sapply(train, class)

```


Decision Tree

```{r}
tree.SP <- tree(SalePrice ~., data = train)
tree.SP

```

